elastic/elastic-stack-testing

playbooks/monitoring/docs_parity.yml
playbooks/monitoring/kibana/docs_compare.py
playbooks/monitoring/kibana/docs_parity.yml

Currently the monitoring parity tests are focussed on Kibana. That is, they are focussed on comparing kibana-indexed monitoring documents with metricbeat-indexed monitoring documents to ensure that there is parity between them.
Going forward we will be requiring similar tests for other products, likely starting with Elasticsearch next.
This PR simply refactors the current setup under `playbooks/monitoring` to make room for kibana and other products in the future.

Monitoring parity: make room for other products

---

playbooks/monitoring/elasticsearch/docs_compare.py

This PR:
- Fixes up the `allowed_insertions` array to be accurate for extra top-level fields allowed in Metricbeat-indexed documents, and
- Handles a special case for documents of `type: index_recovery`

Fixes to Monitoring parity tests for Elasticsearch

---

playbooks/monitoring/docs_parity.yml
playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/elasticsearch/docs_parity.yml

- Monitoring parity tests: Add playbook and script for Elasticsearch  (#29)

[7.x] Monitoring parity tests: Add playbook and script for Elasticsearch (#29)

---

playbooks/monitoring/docs_parity.yml
playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/elasticsearch/docs_parity.yml

- Monitoring parity tests: Add playbook and script for Elasticsearch  (#29)

[7.0] Monitoring parity tests: Add playbook and script for Elasticsearch (#29)

---

playbooks/monitoring/elasticsearch/docs_compare.py

- Fix typo in variable name  (#160)

[7.x] Fix typo in variable name (#160)

---

playbooks/monitoring/elasticsearch/docs_compare.py

- Fixes to Monitoring parity tests for Elasticsearch  (#161)

[7.x] Fixes to Monitoring parity tests for Elasticsearch (#161)

---

playbooks/monitoring/elasticsearch/docs_compare.py

- Fix typo in variable name  (#160)

[7.0] Fix typo in variable name (#160)

---

playbooks/monitoring/elasticsearch/docs_compare.py

- Fixes to Monitoring parity tests for Elasticsearch  (#161)

[7.0] Fixes to Monitoring parity tests for Elasticsearch (#161)

---

playbooks/monitoring/kibana/docs_parity.yml

- Fetch *first* docs (instead of latest) from .monitoring-kibana-*  (#207)

[7.x] Fetch *first* docs (instead of latest) from .monitoring-kibana-* (#207)

---

playbooks/monitoring/kibana/docs_parity.yml

- Fetch *first* docs (instead of latest) from .monitoring-kibana-*  (#207)

[7.0] Fetch *first* docs (instead of latest) from .monitoring-kibana-* (#207)

---

playbooks/monitoring/docs_parity.yml

Backports the following commits to 6.7:
- Fetch *first* docs (instead of latest) from .monitoring-kibana-*  (#207)

[6.7] Fetch *first* docs (instead of latest) from .monitoring-kibana-* (#207)

---

playbooks/monitoring/README.md

- Adding README for monitoring parity tests  (#212)

[7.x] Adding README for monitoring parity tests (#212)

---

playbooks/monitoring/README.md

Backports the following commits to 7.1:
- Adding README for monitoring parity tests  (#212)

[7.1] Adding README for monitoring parity tests (#212)

---

playbooks/monitoring/README.md

- Adding README for monitoring parity tests  (#212)

[7.0] Adding README for monitoring parity tests (#212)

---

playbooks/monitoring/README.md

Backports the following commits to 6.7:
- Adding README for monitoring parity tests  (#212)

[6.7] Adding README for monitoring parity tests (#212)

---

playbooks/monitoring/README.md

- Clarifying supported products in README  (#227)

[7.x] Clarifying supported products in README (#227)

---

playbooks/monitoring/README.md

- Clarifying supported products in README  (#227)

[7.2] Clarifying supported products in README (#227)

---

playbooks/monitoring/README.md

Backports the following commits to 7.1:
- Clarifying supported products in README  (#227)

[7.1] Clarifying supported products in README (#227)

---

playbooks/monitoring/README.md

- Clarifying supported products in README  (#227)

[6.8] Clarifying supported products in README (#227)

---

playbooks/monitoring/elasticsearch/docs_parity.yml

- Fixing typo in file name  (#233)

[7.x] Fixing typo in file name (#233)

---

playbooks/monitoring/elasticsearch/docs_parity.yml

- Fixing typo in file name  (#233)

[7.2] Fixing typo in file name (#233)

---

playbooks/monitoring/elasticsearch/docs_parity.yml

Backports the following commits to 7.1:
- Fixing typo in file name  (#233)

[7.1] Fixing typo in file name (#233)

---

playbooks/monitoring/elasticsearch/docs_parity.yml

- Fixing typo in file name  (#233)

[6.8] Fixing typo in file name (#233)

---

playbooks/monitoring/elasticsearch/docs_compare.py

When the internal/native monitoring method is used, the Elasticsearch production cluster adds a `source_node` field to monitoring documents. Originally the intent of this field was for debugging purposes to know which production cluster node exported the monitoring data to the monitoring cluster.
Unfortunately over time, however, the Monitoring UI came to rely on this field in the case of Elasticsearch monitoring data, specifically for documents with `type:node_stats` or `type:shards`. That's because in such documents, the `source_node` field is _also_ indicative of the Elasticsearch node that the node stats are actually about (for `type:node_stats` documents) or of the Elasticearch node on which the shard lives (for `type:shards` documents).
To account for this misuse, Metricbeat …

Add exceptions for source_node field

---

ansible/roles/xpack_filebeat/tasks/linux/xpack_filebeat_config.yml
playbooks/monitoring/README.md
playbooks/monitoring/beat/docs_compare.py
playbooks/monitoring/beat/docs_parity.yml

- Stack Monitoring parity test for Beats  (#249)

[6.8] Stack Monitoring parity test for Beats (#249)

---

playbooks/monitoring/beat/docs_compare.py
playbooks/monitoring/beat/docs_parity.yml

- Configure Filebeat to send monitoring data via production cluster  (#255)

[7.x] Configure Filebeat to send monitoring data via production cluster (#255)

---

playbooks/monitoring/beat/docs_compare.py
playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/kibana/docs_compare.py

When the list lengths of types differ, print what is different to aid in debugging. 
Produces output like the following:
```
ERROR: Found more internally-indexed document types than metricbeat-indexed document types.
Elements which appear in the internal collector but not in Metricbeat:{'kibana_stats', 'kibana_settings'}
```

Print the diff when list lengths differ

---

playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/elasticsearch/docs_parity.yml

- Various fixes to Elasticsearch parity tests  (#258)

[6.8] Various fixes to Elasticsearch parity tests (#258)

---

playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/elasticsearch/docs_parity.yml

Backports the following commits to 7.3:
- Various fixes to Elasticsearch parity tests  (#258)

[7.3] Various fixes to Elasticsearch parity tests (#258)

---

ansible/roles/elasticsearch/tasks/linux/elasticsearch_is_not_running.yml

ESTF Elasticsearch Monitoring Parity Test build jobs are [failing](https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+master+multijob-elasticsearch/17/console) with the following error:
```
TASK [elasticsearch : Fail if elasticsearch process is running] ****************
14:55:21 fatal: [aithost]: FAILED! => {
14:55:21     "changed": false
14:55:21 }
14:55:21 
14:55:21 MSG:
14:55:21 
14:55:21 elasticsearch is running
```
I [re-ran](https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+master+multijob-elasticsearch/20/console) the same build job but it failed in the same way.
Next, I tried to reproduce this failure locally multiple times but wasn't able to. It always got past the failed task seen in the CI output. 
I can't see logs of what's happening in CI …

Give Elasticsearch more time to shut down

---

playbooks/monitoring/logstash/docs_parity.yml

This PR skips the Logstash parity tests in the `6.8` branch because the `logstash` Metricbeat module isn't available until `7.3.0`.

[6.8] Skip Logstash parity tests

---

ansible/roles/elasticsearch/tasks/linux/elasticsearch_is_not_running.yml
ansible/roles/logstash/tasks/linux/logstash_is_not_running.yml

- Give Logstash more time to shut down  (#303)

[6.8] Give Logstash more time to shut down (#303)

---

ansible/roles/elasticsearch/tasks/linux/elasticsearch_is_not_running.yml
ansible/roles/logstash/tasks/linux/logstash_is_not_running.yml

Backports the following commits to 7.3:
- Give Logstash more time to shut down  (#303)

[7.3] Give Logstash more time to shut down (#303)

---

ansible/roles/elasticsearch/tasks/linux/elasticsearch_is_not_running.yml
ansible/roles/logstash/tasks/linux/logstash_is_not_running.yml

- Give Logstash more time to shut down  (#303)

[7.x] Give Logstash more time to shut down (#303)

---

ansible/roles/xpack_elasticsearch/tasks/linux/xpack_elasticsearch_create_users_roles.yml
ansible/roles/xpack_elasticsearch/tasks/linux/xpack_elasticsearch_set_passwords.yml

I believe we should stop using the `_xpack/security` endpoint, per the deprecation introduced here: https://github.com/elastic/elasticsearch/pull/36293

Prepare for upcoming deprecation of endpoint

---

ansible/roles/xpack_elasticsearch/tasks/linux/xpack_elasticsearch_create_users_roles.yml
ansible/roles/xpack_elasticsearch/tasks/linux/xpack_elasticsearch_set_passwords.yml

Backports #312 
In this case, a backport is not strictly necessary but it should silence some warnings.

[Backport] Prepare for upcoming deprecation

---

playbooks/monitoring/elasticsearch/docs_compare.py

Parity tests began to fail recently and it appears that the problem is that an extra ILM policy is being created. I don't think there is a problem with the parity itself and this is just something that needs to be accounted for in the logic which compares documents. I found that previously, we were just popping off the last document but that this no longer works because the documents are ordered as they previously were.
This simply adjusts the logic to pull out the extra ILM policy from the Metricbeat document in the correct position.
I am not sure of the merge-forward policy in this repo, so this may need a follow-up PR to the master branch after this is reviewed.

[Stack Monitoring] Adjust parity test to pull out correct ILM entry

---

playbooks/monitoring/beat/docs_compare.py
playbooks/monitoring/common/docs_compare_util.py
playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/kibana/docs_compare.py
playbooks/monitoring/logstash/docs_compare.py
requirements.txt

- [Stack Monitoring] Implementing diff in parity tests using dictdiffer  (#353)

[7.x] [Stack Monitoring] Implementing diff in parity tests using dictdiffer (#353)

---

playbooks/monitoring/beat/docs_compare.py
playbooks/monitoring/common/docs_compare_util.py
playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/kibana/docs_compare.py
playbooks/monitoring/logstash/docs_compare.py
requirements.txt

Backports the following commits to 7.4:
- [Stack Monitoring] Implementing diff in parity tests using dictdiffer  (#353)

[7.4] [Stack Monitoring] Implementing diff in parity tests using dictdiffer (#353)

---

playbooks/monitoring/common/docs_compare_util.py
playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/kibana/docs_compare.py
requirements.txt

- [Stack Monitoring] Implementing diff in parity tests using dictdiffer  (#353)

[6.8] [Stack Monitoring] Implementing diff in parity tests using dictdiffer (#353)

---

playbooks/monitoring/common/docs_compare_util.py

This should make it easier for someone debugging the failure to investigate the differences between the docs.

Upon parity failure, print internal- and metricbeat-indexed docs

---

playbooks/monitoring/common/docs_compare_util.py

- Upon parity failure, print internal- and metricbeat-indexed docs.  (#378)

[7.x] Upon parity failure, print internal- and metricbeat-indexed docs. (#378)

---

playbooks/monitoring/common/docs_compare_util.py

Backports the following commits to 7.4:
- Upon parity failure, print internal- and metricbeat-indexed docs.  (#378)

[7.4] Upon parity failure, print internal- and metricbeat-indexed docs. (#378)

---

playbooks/monitoring/common/docs_compare_util.py

Backports the following commits to 7.3:
- Upon parity failure, print internal- and metricbeat-indexed docs.  (#378)

[7.3] Upon parity failure, print internal- and metricbeat-indexed docs. (#378)

---

playbooks/monitoring/common/docs_compare_util.py

- Upon parity failure, print internal- and metricbeat-indexed docs.  (#378)

[6.8] Upon parity failure, print internal- and metricbeat-indexed docs. (#378)

---

playbooks/monitoring/kibana/docs_parity.yml

For the [past several runs](https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+6.8+multijob-kibana/), Stack Monitoring parity tests for Kibana are failing consistently in CI on the `6.8` branch with this error:
```
09:45:24 *** Internally-indexed doc for type='kibana_stats': ***
09:45:24 {'timestamp': '2019-09-30T16:44:43.141Z', 'cluster_uuid': 'xsoEte8rQ2mhs7nULlEtsw', 'interval_ms': 10000, 'kibana_stats': {'response_times': {'max': 0, 'average': 0}, 'process': {'event_loop_delay': 0.9391340000147466, 'memory': {'resident_set_size_in_bytes': 361537536, 'heap': {'size_limit': 1526909922, 'total_in_bytes': 255574016, 'used_in_bytes': 161960000}}, 'uptime_in_millis': 22992}, 'timestamp': '2019-09-30T16:44:42.947Z', 'kibana': {'status': 'green', 'index': '.kibana', …
```

Debugging: print all kibana_stats docs indexed by Metricbeat

---

playbooks/monitoring/beat/docs_compare.py

- Adjust beats parity tests for different file IDs  (#482)

[7.x] Adjust beats parity tests for different file IDs (#482)

---

playbooks/monitoring/beat/docs_compare.py

Backports the following commits to 7.6:
- Adjust beats parity tests for different file IDs  (#482)

[7.6] Adjust beats parity tests for different file IDs (#482)

---

playbooks/monitoring/elasticsearch/docs_compare.py

https://github.com/elastic/elastic-stack-testing/pull/497 didn't quite fix the problem. The `field_types` are now nested with additional properties and this PR ensures we compare only the name

Another fix

---

playbooks/monitoring/README.md
playbooks/monitoring/beat/docs_compare.py
playbooks/monitoring/beat/docs_parity.yml
playbooks/monitoring/common/docs_compare_util.py
playbooks/monitoring/elasticsearch/docs_compare.py
playbooks/monitoring/elasticsearch/docs_parity.yml
playbooks/monitoring/kibana/docs_compare.py
playbooks/monitoring/kibana/docs_parity.yml
playbooks/monitoring/logstash/docs_compare.py
playbooks/monitoring/logstash/docs_parity.yml

- Replace references to "internal" with "legacy"  (#549)

[7.x] Replace references to "internal" with "legacy" (#549)

---

playbooks/monitoring/elasticsearch/docs_compare.py

Beats resolved https://github.com/elastic/beats/issues/18639 but Elasticsearch has yet to work on https://github.com/elastic/elasticsearch/issues/56949 so this PR will special case this to avoid seeing consistent build failures. This can be removed once https://github.com/elastic/elasticsearch/issues/56949 is resolved.

Special case hidden indices

---

playbooks/stack_testing/ci/jenkins_stack_testing.sh

[7.x] Fix build type (#776)

---

ci/kibana/jenkins_kibana_tests.sh
ci/upgrade/buildSrc/src/main/resources/detectionRule.json
ci/upgrade/ess/build.gradle
ci/upgrade/kibana/build.gradle

Following the issue https://github.com/elastic/elastic-stack-testing/issues/932 we are integrating the upgrade framework with the Security Solution Cypress tests.
In order to do that:
- We have created a new gradle task called `run_security_solution_tests` that task is setting the environment variables the Cypress test is going to use for the runner (https://github.com/elastic/kibana/blob/80ab2ff36de6554bd8a5f3a62bc18b971ea057a6/x-pack/test/security_solution_cypress/runner.ts#L153) and is calling the method that is going to actually execute the tests.
- We are extending the `jenkins_kibana_tests.sh` to execute the Cypress tests.

Security Solution Upgrade testing Phase 4: Integrate the upgrade testing framework with Cypress

---

playbooks/monitoring/kibana/docs_parity.yml

https://github.com/elastic/elastic-stack-testing/issues/936
Parity tests when comparing the document count for legacy vs metricbeat indices is sometimes failing with:
```
04:26:10 TASK [Compare legacy-indexed and metricbeat-indexed documents for parity] ******
04:26:10 fatal: [aithost]: FAILED! => {
04:26:10     "changed": true,
04:26:10     "cmd": "python /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/playbooks/monitoring/kibana/docs_compare.py /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/monitoring//kibana/legacy /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/monitoring//kibana/metricbeat",
04:26:10     "delta": "0:00:00.106392",
04:26:10     "end": "2021-07-13 12:24:57.553722", …
```

increase timeout for metricbeat to index documents

---

playbooks/monitoring/kibana/docs_parity.yml

- increase timeout for metricbeat to index (#962)

[7.x] increase timeout for metricbeat to index (#962)

---

playbooks/monitoring/kibana/docs_parity.yml

Backports the following commits to 7.14:
- increase timeout for metricbeat to index (#962)

[7.14] increase timeout for metricbeat to index (#962)

---

playbooks/monitoring/kibana/docs_parity.yml

https://github.com/elastic/elastic-stack-testing/issues/936
Parity tests when comparing the document count for legacy vs metricbeat indices is sometimes failing with:
```
04:26:10 TASK [Compare legacy-indexed and metricbeat-indexed documents for parity] ******
04:26:10 fatal: [aithost]: FAILED! => {
04:26:10     "changed": true,
04:26:10     "cmd": "python /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/playbooks/monitoring/kibana/docs_compare.py /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/monitoring//kibana/legacy /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/monitoring//kibana/metricbeat",
04:26:10     "delta": "0:00:00.106392",
04:26:10     "end": "2021-07-13 12:24:57.553722", …
```

retry metricbeat doc request 5 times

---

playbooks/monitoring/kibana/docs_parity.yml

- retry metricbeat doc request 5 times (#973)

[7.x] retry metricbeat doc request 5 times (#973)

---

ci/upgrade/jobs/ess_upgrade_jobs.yml
ci/upgrade/jobs/ess_upgrade_jobs_7_17.yml
ci/upgrade/jobs/ess_upgrade_jobs_8_2.yml
ci/upgrade/jobs/ess_upgrade_jobs_8_3.yml

Try splitting up jobs for Jenkins by releases and snapshots by version.  This could then be setup to be triggered by RM instead of timer.  Jenkins jobs pending.

Breakup upgrade jobs
