elastic/elastic-stack-testing

README.md, ci/cloud/build.gradle, ci/cloud/buildSrc/build.gradle, ci/cloud/getJavaSdk.sh
[Here](https://github.com/imkarrer/elastic-stack-testing/compare/chicken-or-egg...imkarrer:chicken-or-egg-with-spinup?expand=1) is an extra commit which shows this working!
=> Chicken or egg

playbooks/monitoring/kibana/docs_parity.yml
=> Revert previous change

ansible/ansible.cfg
- Pretty-print Ansible output  (#238)
=> [7.x] Pretty-print Ansible output (#238)

ansible/ansible.cfg
- Pretty-print Ansible output  (#238)
=> [7.2] Pretty-print Ansible output (#238)

ansible/ansible.cfg
Backports the following commits to 7.1:
- Pretty-print Ansible output  (#238)
=> [7.1] Pretty-print Ansible output (#238)

ansible/roles/xpack_filebeat/tasks/linux/xpack_filebeat_config.yml, playbooks/monitoring/README.md, playbooks/monitoring/beat/docs_compare.py, playbooks/monitoring/beat/docs_parity.yml
- Stack Monitoring parity test for Beats  (#249)
=> [7.x] Stack Monitoring parity test for Beats (#249)

ansible/roles/xpack_filebeat/tasks/linux/xpack_filebeat_config.yml, playbooks/monitoring/README.md, playbooks/monitoring/beat/docs_compare.py, playbooks/monitoring/beat/docs_parity.yml
- Stack Monitoring parity test for Beats  (#249)
=> [7.2] Stack Monitoring parity test for Beats (#249)

playbooks/monitoring/elasticsearch/docs_compare.py, playbooks/monitoring/elasticsearch/docs_parity.yml
This PR makes various fixes to the Elasticsearch parity tests. Each commit in this PR is its own fix.
=> Various fixes to Elasticsearch parity tests

playbooks/monitoring/elasticsearch/docs_compare.py, playbooks/monitoring/elasticsearch/docs_parity.yml
- Various fixes to Elasticsearch parity tests  (#258)
=> [7.x] Various fixes to Elasticsearch parity tests (#258)

playbooks/monitoring/elasticsearch/docs_compare.py, playbooks/monitoring/elasticsearch/docs_parity.yml
- Various fixes to Elasticsearch parity tests  (#258)
=> [7.2] Various fixes to Elasticsearch parity tests (#258)

playbooks/monitoring/elasticsearch/docs_compare.py
Backport per https://github.com/elastic/elastic-stack-testing/pull/313#issuecomment-529960265
=> Pull out the correct ILM entry

playbooks/monitoring/kibana/docs_parity.yml
Following in the same vein as #384, this PR will fetch Kibana server logs and print them.
=> Debugging: Fetch and print Kibana logs

ci/cloud/buildSrc/src/main/groovy/org/estf/gradle/ShellCommand.groovy, ci/cloud/common/build.gradle, ci/cloud/ece/build.gradle, ci/kibana/jenkins_kibana_tests.sh
Allow a way to run Kibana PRs on ECE.  Relates to #550.
=> Enable ECE Kibana PRs

ci/kibana/jenkins_kibana_tests.sh, ci/kibana/settings/kibana.yml
- Update docker settings (#667)
=> [7.x] Update docker settings (#667)

playbooks/monitoring/kibana/docs_compare.py
=> Handle some usage exceptions for Kibana monitoring documents

ci/cloud/product/settings/kibana.yml
Ensures the legacy visualization UX is loaded
=> Add showMapvisualizationTypes

ci/cloud/product/settings/kibana.yml
=> [7.x] Add showMapvisualizationTypes (#791)

ci/cloud/product/settings/kibana.yml
Backports the following commits to 7.11:
=> [7.11] Add showMapvisualizationTypes (#791)

ci/cloud/product/settings/kibana.yml
Backports the following commits to 7.10:
=> [7.10] Add showMapvisualizationTypes (#791)

ci/cloud/product/settings/kibana.yml
Backports the following commits to 7.9:
=> [7.9] Add showMapvisualizationTypes (#791)

ci/cloud/product/settings/kibana.yml
Backports the following commits to 7.8:
=> [7.8] Add showMapvisualizationTypes (#791)

ci/cloud/product/settings/kibana.yml
Backports the following commits to 7.7:
=> [7.7] Add showMapvisualizationTypes (#791)
